// Fun English: idioms Lucky acts out and tongue twisters Tali asks for. Pairs are [ru, en] and are voiced by Lucky
// (tools/gen-voices.mjs). Heard ones go to the English tab of the collection.

// Idioms: Lucky says the idiom where it fits (`when`), acts it out literally (`show`, see antics.js idiomShow),
// then explains what it really means (`mean`; the Russian line gives the Russian saying for the same thing).
// `idiom` and `ru` are only for the collection card, `e` is its picture.
export const IDIOMS = [
  { id: 'catsDogs', when: 'cloud', show: 'catsDogs', e: '🐱🌧️🐶', idiom: "It's raining cats and dogs", ru: 'Льёт как из ведра',
    say: ['Ого, с неба льют кошки и собаки!', "Whoa, it's raining cats and dogs!"],
    mean: ['Не бойся! Так по-английски говорят, когда льёт как из ведра.', "Don't worry! That's what we say when it's raining really hard."] },
  { id: 'butterflies', when: 'frog', show: 'butterflies', e: '🦋', idiom: 'Butterflies in my tummy', ru: 'Бабочки в животе',
    say: ['Ой, загадка! У меня бабочки в животике!', "Ooh, a riddle! I've got butterflies in my tummy!"],
    mean: ['Это значит, что я волнуюсь. По-русски тоже говорят: «бабочки в животе».', 'That means I feel a bit nervous and excited.'] },
  { id: 'horses', when: 'fastTaps', show: 'horses', e: '🐎', idiom: 'Hold your horses!', ru: 'Придержи коней!',
    say: ['Тпру! Придержи лошадей!', 'Whoa! Hold your horses!'],
    mean: ['Это значит: «Не спеши, подожди!» По-русски говорят: «Придержи коней!»', 'That means: slow down and wait a moment!'] },
  { id: 'cake', when: 'win', show: 'cake', e: '🍰', idiom: 'A piece of cake', ru: 'Проще пареной репы',
    say: ['Это был кусочек торта!', 'That was a piece of cake!'],
    mean: ['Так говорят, когда что-то очень легко. По-русски: «проще пареной репы».', "That's what we say when something is really easy."] },
  { id: 'allEars', when: 'joke', show: 'allEars', e: '👂', idiom: "I'm all ears", ru: 'Я весь внимание',
    say: ['Я весь — одни уши!', "I'm all ears!"],
    mean: ['Это значит: «Я внимательно слушаю». А для кролика это ещё и правда!', "That means I'm listening really carefully. And for a bunny it's true!"] },
  { id: 'moon', when: 'max', show: 'moon', e: '🌙', idiom: 'Over the moon', ru: 'На седьмом небе',
    say: ['Я прыгаю выше луны!', "I'm over the moon!"],
    mean: ['Это значит: «Я очень-очень счастлив!» По-русски: «на седьмом небе».', 'That means I am super, super happy!'] },
  { id: 'bananas', when: 'play', show: 'bananas', e: '🍌', idiom: 'Go bananas', ru: 'Сходить с ума от радости',
    say: ['Ура! Я сейчас пойду бананами!', "Yay! I'm going bananas!"],
    mean: ['Так говорят, когда ты так рад, что скачешь как сумасшедший. По-русски: «с ума сойти от радости».', 'Going bananas means getting really, really excited.'] },
  { id: 'weather', when: 'low', show: 'weather', e: '🌧️', idiom: 'Under the weather', ru: 'Мне что-то не по себе',
    say: ['Я сегодня немножко под погодой…', "I'm feeling a bit under the weather…"],
    mean: ['Это значит: «Мне немножко нехорошо». По-русски: «мне что-то не по себе».', 'That means I feel a little bit poorly.'] },
  { id: 'hay', when: 'sleepSoon', show: 'hay', e: '🌾', idiom: 'Hit the hay', ru: 'Пора на боковую',
    say: ['Скоро пора ударить по сену!', 'Soon it will be time to hit the hay!'],
    mean: ['Hit the hay значит «пойти спать». По-русски: «пора на боковую». А я правда сплю на сене!', 'Hit the hay means go to bed. And I really do sleep on hay!'] },
  { id: 'log', when: 'morning', show: 'log', e: '🪵', idiom: 'Sleep like a log', ru: 'Спать без задних ног',
    say: ['Доброе утро! Я спал как бревно!', 'Good morning! I slept like a log!'],
    mean: ['Это значит, что я спал крепко-крепко. По-русски: «спал без задних ног».', 'That means I slept really, really well.'] },
  { id: 'earlyBird', when: 'early', show: 'earlyBird', e: '🐦🪱', idiom: 'The early bird catches the worm', ru: 'Кто рано встаёт, тому Бог подаёт',
    say: ['Ранняя птичка ловит червячка!', 'The early bird catches the worm!'],
    mean: ['Это значит: кто начинает пораньше, успевает больше. По-русски: «Кто рано встаёт, тому Бог подаёт».', 'That means people who start early get the best things.'] },
  { id: 'fish', when: 'newWorld', show: 'fish', e: '🐟', idiom: 'A fish out of water', ru: 'Не в своей тарелке',
    say: ['Ой, я тут как рыба без воды!', 'Oh, I feel like a fish out of water here!'],
    mean: ['Это значит, что всё вокруг новое и непривычное. По-русски: «не в своей тарелке».', 'That means everything here is new and strange to me.'] },
  { id: 'catBag', when: 'surprise', show: 'catBag', e: '👜🐱', idiom: 'Let the cat out of the bag', ru: 'Проболтаться',
    say: ['Ой! Я выпустил кошку из мешка!', 'Oops! I let the cat out of the bag!'],
    mean: ['Это значит, что я случайно выдал секрет: там сюрприз! По-русски: «проболтался».', "That means I told a secret by accident: there's a surprise!"] },
  { id: 'littleBird', when: 'missionHint', show: 'littleBird', e: '🐦', idiom: 'A little bird told me', ru: 'Сорока на хвосте принесла',
    say: ['Мне птичка напела, что в Додзё новое задание!', 'A little bird told me there is a new mission in the Dojo!'],
    mean: ['Так говорят, когда не хотят выдавать, кто рассказал. По-русски: «сорока на хвосте принесла».', "That's what we say when we don't want to tell who told us."] },
  { id: 'bee', when: 'planDone', show: 'bee', e: '🐝', idiom: 'Busy as a bee', ru: 'Как белка в колесе',
    say: ['Уф! Сегодня я был занят, как пчела!', 'Phew! I was as busy as a bee today!'],
    mean: ['Это значит, что я переделал кучу дел. По-русски: «кручусь как белка в колесе».', 'That means I did lots and lots of things.'] },
  { id: 'cucumber', when: 'calm', show: 'cucumber', e: '🥒', idiom: 'Cool as a cucumber', ru: 'Спокоен как удав',
    say: ['Теперь я спокоен, как огурец!', "Now I'm as cool as a cucumber!"],
    mean: ['Это значит: «очень спокойный». По-русски говорят: «спокоен как удав».', 'That means really calm and relaxed.'] },
  { id: 'couchPotato', when: 'playedLong', show: 'couchPotato', e: '🛋️🥔', idiom: 'A couch potato', ru: 'Лежебока',
    say: ['Кажется, мы с тобой превращаемся в диванные картошки!', "I think we're turning into couch potatoes!"],
    mean: ['Couch potato — это тот, кто весь день сидит на диване. Пойдём лучше поиграем на улице!', "A couch potato is someone who sits on the sofa all day. Let's go and play outside!"] },
  { id: 'pigs', when: 'idle', show: 'pigs', e: '🐷', idiom: 'When pigs fly', ru: 'Когда рак на горе свистнет',
    say: ['Я перестану любить морковку, когда свиньи полетят!', "I'll stop loving carrots when pigs fly!"],
    mean: ['Это значит: «никогда!» По-русски: «когда рак на горе свистнет».', 'That means never ever!'] },
  { id: 'frogThroat', when: 'twister', show: 'frogThroat', e: '🐸', idiom: 'A frog in my throat', ru: 'В горле першит',
    say: ['Кхм-кхм! У меня лягушка в горле!', "Ahem, ahem! I've got a frog in my throat!"],
    mean: ['Это значит, что голос немножко охрип. По-русски: «в горле першит».', 'That means my voice is a bit croaky.'] },
  { id: 'biteOff', when: 'treat', show: 'biteOff', e: '🥕', idiom: 'Bite off more than you can chew', ru: 'Взяться за непосильное',
    say: ['Ой, я откусил больше, чем могу прожевать!', "Oops, I've bitten off more than I can chew!"],
    mean: ['Это значит, что взялся сразу за слишком многое. По-русски: «замахнулся не по силам».', 'That means I tried to do too much at once.'] },
  { id: 'blueMoon', when: 'rare', show: 'blueMoon', e: '🔵🌙', idiom: 'Once in a blue moon', ru: 'Раз в сто лет',
    say: ['Такое бывает раз в голубую луну!', 'That only happens once in a blue moon!'],
    mean: ['Это значит: «очень-очень редко». По-русски: «раз в сто лет».', 'That means very, very rarely.'] },
  { id: 'clouds', when: 'back', show: 'clouds', e: '☁️', idiom: 'Head in the clouds', ru: 'Витать в облаках',
    say: ['Ой, прости, у меня голова была в облаках!', 'Oh, sorry, I had my head in the clouds!'],
    mean: ['Это значит, что я замечтался и не слушал. По-русски тоже говорят: «витать в облаках».', 'That means I was daydreaming and not paying attention.'] },
];

// Tongue twisters: Tali asks, Lucky says one slowly, faster and super fast (the same clip, played faster),
// then it's the child's turn. `t` is [Russian meaning, English twister].
export const TWISTERS = [
  { id: 'seashells', t: ['Она продаёт ракушки на берегу моря.', 'She sells seashells by the seashore.'] },
  { id: 'lorry', t: ['Красный грузовик, жёлтый грузовик.', 'Red lorry, yellow lorry, red lorry, yellow lorry.'] },
  { id: 'peterPiper', t: ['Питер Пайпер набрал горсть маринованных перчиков.', 'Peter Piper picked a peck of pickled peppers.'] },
  { id: 'woodchuck', t: ['Сколько дров накидал бы сурок, если бы сурок умел кидать дрова?', 'How much wood would a woodchuck chuck if a woodchuck could chuck wood?'] },
  { id: 'fuzzyWuzzy', t: ['Пушистик был медведем. У Пушистика не было шерсти. Выходит, Пушистик был не пушистый?', "Fuzzy Wuzzy was a bear. Fuzzy Wuzzy had no hair. Fuzzy Wuzzy wasn't fuzzy, was he?"] },
  { id: 'skeletons', t: ['Шесть липких скелетов.', 'Six sticky skeletons.'] },
  { id: 'uniqueNY', t: ['Уникальный Нью-Йорк, уникальный Нью-Йорк.', 'Unique New York, unique New York.'] },
  { id: 'toyBoat', t: ['Игрушечная лодка, игрушечная лодка, игрушечная лодка.', 'Toy boat, toy boat, toy boat.'] },
  { id: 'betty', t: ['Бетти Боттер купила масла, но масло было горьким.', 'Betty Botter bought some butter, but the butter was bitter.'] },
  { id: 'iScream', t: ['Я кричу, ты кричишь, мы все кричим: «Мороженое!»', 'I scream, you scream, we all scream for ice cream!'] },
  { id: 'blackBug', t: ['Большой чёрный жук укусил большого чёрного медведя.', 'A big black bug bit a big black bear.'] },
  { id: 'sillySally', t: ['Глупышка Салли быстро прогнала семь глупеньких овечек.', 'Silly Sally swiftly shooed seven silly sheep.'] },
  { id: 'wristwatch', t: ['Ирландские наручные часы, швейцарские наручные часы.', 'Irish wristwatch, Swiss wristwatch.'] },
  { id: 'fourFish', t: ['Четыре прекрасные свежие рыбки для тебя.', 'Four fine fresh fish for you.'] },
  { id: 'whichWitch', t: ['Какая ведьма какая? Какая ведьма какая?', 'Which witch is which? Which witch is which?'] },
  { id: 'kitty', t: ['Кошка поймала котёнка на кухне.', 'Kitty caught the kitten in the kitchen.'] },
  { id: 'greekGrapes', t: ['Греческий виноград, греческий виноград.', 'Greek grapes, Greek grapes, Greek grapes.'] },
  { id: 'freeThrows', t: ['Три свободных броска, три свободных броска.', 'Three free throws, three free throws.'] },
  { id: 'walrus', t: ['Уэйн поехал в Уэльс смотреть на моржей.', 'Wayne went to Wales to watch walruses.'] },
  { id: 'lollipops', t: ['Лаки лижет чудесные маленькие леденцы.', 'Lucky licks lovely little lollipops.'] },
  { id: 'taliTail', t: ['Крошечный хвостик {dog} дёргается десять раз.', "{dog}'s tiny tail twitches ten times."] },
  { id: 'bunnies', t: ['Весёлые кролики прыгают на больших синих шариках.', 'Busy bunnies bounce on big blue balloons.'] },
];

export const IDIOM_BY_ID = Object.fromEntries(IDIOMS.map((x) => [x.id, x]));
export const TWISTER_BY_ID = Object.fromEntries(TWISTERS.map((x) => [x.id, x]));
